export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const ADD_RESERVATION = 'ADD_RESERVATION';

export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';

export const GET_DEGREES = 'GET_DEGREES';
export const DELETE_DEGREE = 'DELETE_DEGREES';
export const ADD_DEGREE = 'ADD_DEGREE';

export const GET_STUDENTS = 'GET_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';

export const GET_COMPUTER_LABS = 'GET_COMPUTER_LABS';
export const DELETE_COMPUTER_LAB = 'DELETE_COMPUTER_LAB';
export const ADD_COMPUTER_LAB = 'ADD_COMPUTER_LAB';

export const GET_ROOMS = 'GET_ROOMS';
export const DELETE_ROOM = 'DELETE_ROOM';
export const ADD_ROOM = 'ADD_ROOM';

export const GET_LABS = 'GET_LABS';
export const DELETE_LAB = 'DELETE_LAB';
export const ADD_LAB = 'ADD_LAB';

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_RESERVATIONS = 'CLEAR_RESERVATIONS';