# Generated by Django 3.2 on 2021-05-27 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id_akademika', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_akademika', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Akademiki',
            },
        ),
        migrations.CreateModel(
            name='Kierunek',
            fields=[
                ('id_kierunku', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_kierunku', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Kierunki',
            },
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id_pokoju', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_lozek', models.IntegerField()),
                ('opis', models.TextField()),
                ('id_akademika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.akademik')),
            ],
            options={
                'verbose_name_plural': 'Pokoje',
            },
        ),
        migrations.CreateModel(
            name='Pomieszczenie',
            fields=[
                ('id_pomieszczenia', models.AutoField(primary_key=True, serialize=False)),
                ('opis', models.TextField()),
                ('rodzaj_pom', models.CharField(choices=[('S', 'Sala'), ('L', 'Laboratorium'), ('P', 'Pracownia'), ('A', 'Aula wykladowa')], default='S', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Pomieszczenia',
            },
        ),
        migrations.CreateModel(
            name='Wydzial',
            fields=[
                ('id_wydzialu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_wydzialu', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Wydziały',
            },
        ),
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('pomieszczenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reservations.pomieszczenie')),
                ('nr_laboratorium', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_miejsc', models.IntegerField()),
                ('czy_rzutnik', models.BooleanField()),
                ('osprzet', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Laboratoria',
            },
            bases=('reservations.pomieszczenie',),
        ),
        migrations.CreateModel(
            name='PracowaniaSpecjalistyczna',
            fields=[
                ('pomieszczenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reservations.pomieszczenie')),
                ('nr_pracowni', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_miejsc', models.IntegerField()),
                ('czy_rzutnik', models.BooleanField()),
                ('osprzet', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Pracownie Specjalistyczne',
            },
            bases=('reservations.pomieszczenie',),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('pomieszczenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reservations.pomieszczenie')),
                ('nr_sali', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_miejsc', models.IntegerField()),
                ('czy_rzutnik', models.BooleanField()),
                ('jaka_tablica', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sale',
            },
            bases=('reservations.pomieszczenie',),
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id_uzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=25)),
                ('e_mail', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=15)),
                ('id_wydzialu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wydzial')),
                ('konto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('ECTS', models.IntegerField()),
                ('isObligatory', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('W', 'Wykład'), ('C', 'Ćwiczenia'), ('L', 'Laboratorium'), ('P', 'Pracownia Specjalistyczna'), ('S', 'Seminarium')], default='R', max_length=1)),
                ('subject_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wydzial')),
            ],
            options={
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nr_indeksu', models.AutoField(primary_key=True, serialize=False)),
                ('nr_telefonu', models.IntegerField()),
                ('id_kierunku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.kierunek')),
                ('id_uzytkowanika', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.uzytkownik')),
            ],
            options={
                'verbose_name_plural': 'Studenci',
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaSali',
            fields=[
                ('id_rezerwacji_sali', models.AutoField(primary_key=True, serialize=False)),
                ('cykliczny', models.BooleanField(default=False)),
                ('how_many_times', models.IntegerField(default=1)),
                ('data_od', models.DateTimeField()),
                ('data_do', models.DateTimeField()),
                ('data_wykonania_rezerwacji', models.DateTimeField(default=datetime.datetime(2021, 5, 27, 10, 47, 8, 394704, tzinfo=utc))),
                ('status', models.CharField(choices=[('Z', 'Zaakceptowana'), ('O', 'Odrzucona'), ('R', 'W trakcie rozpatrywania')], default='R', max_length=1)),
                ('opis', models.TextField(default='', max_length=200)),
                ('id_pomieszczenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.pomieszczenie')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje_sal', to='reservations.uzytkownik')),
                ('przedmiot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.subject')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje Sal',
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaPokoju',
            fields=[
                ('id_rezerwacji_pokoju', models.AutoField(primary_key=True, serialize=False)),
                ('data_od', models.DateTimeField()),
                ('data_do', models.DateTimeField()),
                ('data_wykonania_rezerwacji', models.DateTimeField(default=datetime.datetime(2021, 5, 27, 10, 47, 8, 396703, tzinfo=utc))),
                ('status', models.CharField(choices=[('Z', 'Zaakceptowana'), ('O', 'Odrzucona'), ('R', 'W trakcie rozpatrywania')], default='R', max_length=1)),
                ('id_pokoju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.pokoj')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.uzytkownik')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje Pokoi',
            },
        ),
        migrations.AddField(
            model_name='pomieszczenie',
            name='id_wydzialu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wydzial'),
        ),
        migrations.AddField(
            model_name='pomieszczenie',
            name='opiekun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.uzytkownik'),
        ),
        migrations.AddField(
            model_name='kierunek',
            name='id_wydzialu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wydzial'),
        ),
    ]
