# Generated by Django 3.0.5 on 2020-11-23 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id_akademika', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_akademika', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Akademiki',
            },
        ),
        migrations.CreateModel(
            name='Kierunek',
            fields=[
                ('id_kierunku', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_kierunku', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Kierunki',
            },
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id_pokoju', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_lozek', models.IntegerField()),
                ('opis', models.TextField()),
                ('id_akademika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Akademik')),
            ],
            options={
                'verbose_name_plural': 'Pokoje',
            },
        ),
        migrations.CreateModel(
            name='Pomieszczenie',
            fields=[
                ('id_pomieszczenia', models.AutoField(primary_key=True, serialize=False)),
                ('opis', models.TextField()),
                ('rodzaj_pom', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Pomieszczenia',
            },
        ),
        migrations.CreateModel(
            name='Wydzial',
            fields=[
                ('id_wydzialu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_wydzialu', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Wydziały',
            },
        ),
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('pomieszczenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reservations.Pomieszczenie')),
                ('nr_laboratorium', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_miejsc', models.IntegerField()),
                ('czy_rzutnik', models.BooleanField()),
                ('osprzet', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Laboratoria',
            },
            bases=('reservations.pomieszczenie',),
        ),
        migrations.CreateModel(
            name='PracowaniaSpecjalistyczna',
            fields=[
                ('pomieszczenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reservations.Pomieszczenie')),
                ('nr_pracowni', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_miejsc', models.IntegerField()),
                ('czy_rzutnik', models.BooleanField()),
                ('osprzet', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Pracownie Specjalistyczne',
            },
            bases=('reservations.pomieszczenie',),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('pomieszczenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reservations.Pomieszczenie')),
                ('nr_sali', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_miejsc', models.IntegerField()),
                ('czy_rzutnik', models.BooleanField()),
                ('jaka_tablica', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sale',
            },
            bases=('reservations.pomieszczenie',),
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id_uzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=25)),
                ('e_mail', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=15)),
                ('id_wydzialu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Wydzial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nr_indeksu', models.AutoField(primary_key=True, serialize=False)),
                ('nr_telefonu', models.IntegerField()),
                ('id_kierunku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Kierunek')),
                ('id_uzytkowanika', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.Uzytkownik')),
            ],
            options={
                'verbose_name_plural': 'Studenci',
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaSali',
            fields=[
                ('id_rezerwacji_sali', models.AutoField(primary_key=True, serialize=False)),
                ('data_od', models.DateTimeField()),
                ('data_do', models.DateTimeField()),
                ('data_wykonania_rezerwacji', models.DateTimeField(default=datetime.datetime(2020, 11, 23, 10, 56, 18, 844195))),
                ('id_pomieszczenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Pomieszczenie')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje_sal', to='reservations.Uzytkownik')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje Sal',
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaPokoju',
            fields=[
                ('id_rezerwacji_pokoju', models.AutoField(primary_key=True, serialize=False)),
                ('data_od', models.DateTimeField()),
                ('data_do', models.DateTimeField()),
                ('data_wykonania_rezerwacji', models.DateTimeField(default=datetime.datetime(2020, 11, 23, 10, 56, 18, 845695))),
                ('id_pokoju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Pokoj')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Uzytkownik')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje Pokoi',
            },
        ),
        migrations.AddField(
            model_name='pomieszczenie',
            name='id_wydzialu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Wydzial'),
        ),
        migrations.AddField(
            model_name='kierunek',
            name='id_wydzialu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Wydzial'),
        ),
    ]
