# Generated by Django 3.2 on 2021-05-31 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210527_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoj',
            name='nr_pietra',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokoj',
            name='nr_pokoju',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 11, 8, 39, 609794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 11, 8, 39, 608293, tzinfo=utc)),
        ),
    ]
