# Generated by Django 3.1.7 on 2021-03-01 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20210224_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomieszczenie',
            name='rodzaj_pom',
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 14, 14, 270367)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 14, 14, 267867)),
        ),
    ]
