# Generated by Django 3.1.7 on 2021-03-01 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20210301_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomieszczenie',
            name='rodzaj_pom',
            field=models.CharField(default='S', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 30, 32, 609844)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 30, 32, 607343)),
        ),
    ]
