# Generated by Django 3.1.7 on 2021-03-01 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20210301_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomieszczenie',
            name='rodzaj_pom',
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 36, 10, 241388)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 36, 10, 239387)),
        ),
    ]
