# Generated by Django 3.1.7 on 2021-03-01 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20210301_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomieszczenie',
            name='rodzaj_pom',
            field=models.CharField(choices=[('S', 'Sala'), ('L', 'Laboratorium'), ('P', 'Pracownia'), ('A', 'Aula wykladowa')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 43, 19, 794853)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 9, 43, 19, 792353)),
        ),
    ]
