# Generated by Django 3.1.7 on 2021-03-03 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20210301_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacjapokoju',
            name='status',
            field=models.CharField(choices=[('Z', 'Zaakceptowana'), ('O', 'Odrzucona'), ('R', 'W trakcie rozpatrywania')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='rezerwacjasali',
            name='status',
            field=models.CharField(choices=[('Z', 'Zaakceptowana'), ('O', 'Odrzucona'), ('R', 'W trakcie rozpatrywania')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 12, 27, 35, 861466)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 12, 27, 35, 858966)),
        ),
    ]
