# Generated by Django 3.1.7 on 2021-03-05 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_auto_20210305_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 18, 8, 31, 784035)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 18, 8, 31, 781036)),
        ),
        migrations.CreateModel(
            name='Zajecie',
            fields=[
                ('id_zajecia', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_zajecia', models.CharField(max_length=50)),
                ('kod_zajecia', models.CharField(max_length=10)),
                ('punkty_ECTS', models.IntegerField()),
                ('rodzaj', models.CharField(choices=[('R', 'Obowiązkowy'), ('O', 'Obieralny')], default='R', max_length=1)),
                ('jednostka_zajecia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wydzial')),
            ],
            options={
                'verbose_name_plural': 'Zajęcia',
            },
        ),
    ]
