# Generated by Django 3.2 on 2021-04-20 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20210418_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomieszczenie',
            name='opiekun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.uzytkownik'),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 5, 30, 321295)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 20, 5, 30, 319795)),
        ),
    ]
