# Generated by Django 3.2 on 2021-04-23 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_auto_20210420_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zajecie',
            new_name='Przedmiot',
        ),
        migrations.AlterModelOptions(
            name='przedmiot',
            options={'verbose_name_plural': 'Przedmioty'},
        ),
        migrations.AddField(
            model_name='rezerwacjasali',
            name='przedmiot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.przedmiot'),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 12, 23, 30, 932728)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 12, 23, 30, 931226)),
        ),
    ]
