# Generated by Django 3.2 on 2021-04-23 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20210423_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 12, 29, 10, 44506)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 12, 29, 10, 43007)),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('ECTS', models.IntegerField()),
                ('isObligatory', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('W', 'Wykład'), ('C', 'Ćwiczenia'), ('L', 'Laboratorium'), ('P', 'Pracownia Specjalistyczna'), ('S', 'Seminarium')], default='R', max_length=1)),
                ('subject_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.wydzial')),
            ],
            options={
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='przedmiot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.subject'),
        ),
        migrations.DeleteModel(
            name='Przedmiot',
        ),
    ]
