# Generated by Django 3.2 on 2021-05-08 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_auto_20210423_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacjasali',
            name='opis',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 10, 46, 24, 719125)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 10, 46, 24, 717127)),
        ),
    ]
